
import java.awt.Point;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;

public class TwelveFive {
    // static String input = """
    // RRRRIICCFF
    // RRRRIICCCF
    // VVRRRCCFFF
    // VVRCCCJFFF
    // VVVVCJJCFE
    // VVIVCCJJEE
    // VVIIICJJEE
    // MIIIIIJJEE
    // MIIISIJEEE
    // MMMISSJEEE
    // """;

    static String input = """
    CCKKKKKKKLLLLLLLLLLLLLLLLLSQQQQQQQQQQQQQQQQQQQQQQQQRRQQQQQQQQQQGGGGGGIIIIIIIPPPPPPPPPNNNNNNNNNNIIIIIIIIRRRRRRRRRRRUUUUUUUUUUTTTTTTNTTTTTTTTT
    KKKKKKKLLLLLLLLLLLLLLLLLLLLQQQQQQQQQQQQQQQQQQQQQQQRRRRRRQQQQQQQGGGGGGGIIIIIPPPPPPPPPPNNNNNNNNNNIIIIIIIIRRRRRRRRRRUUUUUUUUUUUTTTTTTTVTTTHHTTT
    KKKKKKCQQQLLLLLLLLLLLLLLLTQQQQQJQQQQQQQQQQQQQQQQQQRRRRRRRQRQQQGGGGGGGGGIIIIIIPPPPPPPPPPPNNNNNNNNIIIIIRRRRRRRRRRRRRRUUUUUUTTTTTTTTTTTTTTHHWWT
    QIIKKKKQQQLQLLLLLLLLLLLLLLQSSQJJQQQQQQQQQQQQQQQQRRRRRRRRRRRQGGGGGGGGQQZZIIIIIPPPPPPPPPPNNNNNNNNNIIIIIIRRRRRRRRRRRRRUUUUUUTKKTCTTTTVVTTWHHWWW
    QQIKKKQQQQQQQLLLLLLLLLLLLLSSSJJJJQJQQJQQQQQQQQQQRRRRRRRRRRRRGGGGGGGGZZZZIIIPPPPPPPPPNNNNNNNNNNNNIIIIIIIRRRRRRRRRRRRUUUUUCCKCGCTTTTTTTWWHHWWW
    QQQKKQQQQQQQQLLDDLLLLLLLLSSSJJJJJJJJJJQQQQQQQQQQQQRRRRRRRRRRGGGGGGGGGZZZIIIPPPPPPPPPPMNNNNNNNNNNIIIIIIIIRRRRRRRRRRRUUUURRCCCCCTTTTTWWWWWWWWW
    QQQQQQQQQQQQLLLDDLLLLLSSLSSSJJJJJJJJJJQQQDDDDQQQQQQRRRRRRRRRGGGGGGGGGZZIIIPPPPPPPPPPPMMNNNNNNNNIIIIIIIIISSRRRRRRRRRRRRRRRCCCCCTTTTTWWWWWWWWW
    QQQQQQQQQQQLLLLDOLLLXLSSSSSSJJJJJJJJJJJQQDDDMMMMMMMMMMRRRRRRGGGGGGGGGZZZJIPIPPPPPPPPHWMWNNNNNNIIIIIISSSIVVVRRRRRUFRQRRRRCCCCCCCTTTTWWWWWWWWW
    QQQQQQQQQQQLLLLDDDDDDSSSSSSJJJJJJJJJJJQQQQQDMMMMMMMMMMRRRRRGGGGGGGGGGJJBJIIIIPPPPPPWHWWWWNNNNNIIISSSSSSYVVVRRRVRFFFFURRRZCCCCCCSTTTTWWDWDWWW
    QQQQQQQQQQQQQDDDDDDDDSSSSSSSJJJJJJJJJJDQQDDDMMMMMMMMMMURRRRGGGGGGGGGGJJJJJIIIPPPPPWWWWWWZNNNIIIIIISSSVVVVVVVRVVFFFFFUSRRCCCCCCCSSWWWWWDDDDWW
    PPQQQQQQQQKQDDDDDDDDDDDSSSSSJJJDJIMJJPDDDWDDMMMMMMMMMMURRRRGGGGGGGGGJJJJJJIIIPPPSPWWWWWWWZZZCCCIIIXSVVVVVVVVRVVVVFFSSSSRCCCCCCCSSWDDWWWDDDDW
    PPQQTQQQQKKKDDDDDDDDDDDDDSSSJJMMMMMPPPPDDDDDMMMMMMMMMMRRRDRGGGGGGJJJJJJJJJIIIIPPWWWWWWWWWCZZCCCIIIXVVVVVVVVVVVVVVVFSSSRRCCCCCCSSSSDDDWWDDDWW
    PPPQPQQNQKKKKKKDDDDDDDDDURSSSMMMMMMMMPPPPDDDMMMMMMMMMMUDEDODDGGGGJJJJJJJJJJJBIPWWWWWWWWWCCZCCCCIIXXXXWVVVVVVVVVVVVVVYCCCCCCCCCSSSSDDDDDDDDDD
    PPPPPQQPPPKKKKKDDDDDDUUUURRRSMMMMMMMMMPPDDDDMMMMMMMMMMDDDDDDDGGGGGJJJJJJJJJBBBDDDWWWWWWCCCCCCCXXXXWWWWVVVVVVVVJJJVVVYCCCCCCLSSSSSSVDDDDDDDDD
    PPPPPPPPPJKKKKDDDDDUUUUURRRSSMMMMMMMLLPDDDDDDDDDDDDDDDDDDDDDDGGGGGGGJDJPPDDDDDDDDWWWWWWWWCCCCCCWWWWWWWWWVVVVVVJJJJWWJCCCCCLLSSSSSSSSSDDDDDDD
    PPPPPPPPPPKKKKDDHDUUUUURRRRRRRMMMMMMLLLLLDDDDDDDDDDDDTDDDGGGGGGGGGGGGDPPDDDDDDDDDDDWWWWWWCCCCCWWWWWNWWWWWVVVVVJJJJJJJJCCCCLLSSSSSSSSBDDDDDDD
    PPPPPPPPKKKKKKKKKKUUUUURRRRRRMMMMMLLLLLLLKKDDDDDDSSDDDDDDGGGGGGGGGGDDDDPPDDDDDDDDDDWWWGGGGGGGGGGWWWWWWWWWWVVVVVJJJJJJJJCCCCCSSSSSSSSSSDDDDDK
    PPPPFFPPPKKKKKKKKKUUKURRRRRRRMJMMMMLLLLLLKKDDDDDSSSSDBDDDHHHGGGGGGDDDDDDDDDDDDDDDDDDDWGGGGGGGGGGWWWWWWWWWVVVVVVJJJJJJJJJCCCCSSSSSSSSDDDDDDDD
    PPFPFFPPPKKKKKKKKKKKKULRRRMMMMMMMMMLLLLLLLDDDDSSSSSSUBBBDDHHHGGHHGHDDDDDDDDDDDDDDDDDDDGGGGGGGGGGWWWWWWWWWWWVVVVJCJJJJJJJCHHSGSSSSSSSSDDDDDDD
    EEFFFPPPKKKKKKKKKKKKKULLRRRMMMMMMMMLLLLLLLBBSSSSWSSSSSBBDHHHHHHHHHHHDDDDDDDDDDDDDDDDGGGGGGGGGGGGWWWWWIIIIVVVVVJJCJJJJJJHHHSSSSSSSSSSSDDDDDQQ
    EEFFEPPKKKKKKKLLLKKKKULLRRRRMMMMMMMMLULLLLBBSSSSSSSSSSBCCCCCCCCCHHHDDDDDDDDDDDDDDDDDGGGGGGGGGGGGWWWWISIIIIIVVVVVVNNJJJJJJSSSSSSSSSSSSSDDDDDQ
    EEEEEKKKKKKKKKLLLKLLLLLRRRRRRMMMLMMMLRRRLBBBBSSSSSSSSSSCCCCCCCCCHHHDDDDDDDDDDDDDDDDDGGGGGGGGGGGGWWWRIIIIIIIIVVVVVNJJJJJJSSSSSSSSSSSSSSDDDDDQ
    EEEEEEKKKKKGKKLLLLLLLLLLLRRRRRRRLLLRRRRRLBBBSSSSSSSSSSSCCCCCCCCCCHHDDDDFDDDDDDDDDDDDGGGGGGGGGGGGWWRGGGGGGGIAVVVVJJJJJJJJSSSSSSSSSSSSSSDDDDDD
    EEEEFGGGGGKGGGLLLLLLLLLLLRRRRRRRLLLRRRRRBBBBBSSSSSSSSSCCCCCCCCCCCHDDDDDFDLDDDDDDDDDDGGGGGGGGGGGGGGGGGGGGGGIIIVJJJJJJJJIIISIISSSSRSSSSSDDDDKK
    ECCCCGCGGGGGGGLLLLLLLLLMRRRRRRRRLLLLLRRCBBBCSSSSSSSSSSCCCCCCCCCCCHDDDDDFDLDDDDDDDDDDGGGGGGGGGGGGGGGGGGGGGGIVVVVVJJJJJJIIIIIRESSSRRSRRSRRKDKK
    ECCCCGGGGGGGGLLLLLLLLLLLRRRRRRRRRLLLCCCCBBCCCDSSSSSSSSCCCCCCCCCCCDDDDDDDDLDDDDDDDDCCGGGGGGGGGGGGGGGGGGGGGGIVVVVXXXJJXXXIIRRRRRRSRRRRRRRRKKKK
    CCCCUGGGGGGGGLULLLLLLSSSRRRRRRRRLLLLLCCCCCCCCSSSSSSSSSCCCCCCCCCIIIDDIDDDDLLLLDDDDDCCGGGGGGGGCCCCCCRGGGGGGGFVVVXXXJJJXXXIIIRRRRRRRRRRRRRRRKKK
    CCCCCCGMGGGGGLLLLLLLLSSSSSSRRRRRRLLLLLCCCCCCCSBSSSSSSSCCCCCCCCCQIIIDIDDRDDLLLDDDDDCCGGGGGGGGCCCCCRRGGGGGGGFFFVVXXXXXXXXXIRRRRRRRRRRRRRRRRRKK
    CCCCCCCCGGGGLLLLLLLLLLLSWSSRRLRLLLLLPLLCCCCCCSSSSSSSSSCCCCCCCCCQQIIIIIDDDDLLLLLDDLCCCCCGGGGGPCCCCRRGGGGGGGFFFFVXXXXXXXEXXRRRRRRSRRRRRRRRRRRK
    CCCCCCCCGGGGGGGLLLLLLSSSWWRRLLLLLLLLPCCCCCCCCSNSSSSSSSCCCCCCCCCQIIIIIIDKKLLLLLLLDLLLCCCGGGGGPPPPRRNGGGGGGGNFFXXXXXXXXXXXDRRRRSSSSSRSSRRRKKKK
    CCCCCCCCCGGGGGLLLLLLSSSSWWRRLLLLLPPPPPCCCCCCCCNNNSSSMMCCCCCCCCCIIIIIIKKKKLLLLLLLLLLLCCCGGGGGPPPPRRNNNNNNNNNFFXXXXXXXXXIIGGGGGSSSSRRSSRRSSSKK
    CCHCCCTCMMGGGSSSSLSSSSSSWWTRLLLLYYPPPPPCNCCCCNNNSSSSSMCCCCCCCCCIIIIIKKKKKLLLLLLLLLVVVPPPPPPPPPPNNNNNNNNNNNNFFXFXXXXXXXXIIGGGCSSSSSRSSSSSSKKK
    CCCCCWTTGGSSSSSSSSSSSSWWWWLLLYYYYYPPPPMNNNCCCNNNSSSSMMCCCCCCCCCIIIIIKKKKKKKLLLLLLLVVVVPPPPPPPPPNNNNNNNNNNNNNFFFXGXEXXXIIIIGGCSSSSSSSSSSSKKKK
    CIIIWWTTTGGGGGGGGSSSSSSSWSSLLYYYYYYPPPNNNNNNNNNNNSMMMMMMMMMMMIIIIIKKKKKKKKKKKILLLLVVVVPPPPPPPPPPNNNNNNNNNNNNFFFFFEEEXXIIIIGGGSSSSSSSSSKKKKKK
    IIIWWTTTGGGGGGGGGGGSSSSSSSSSYYYYYYYYYYNNNNNNNNNNNSMMMMMMMMMIIIIIIIIKKKKKKKKKKKLLLLVVVVPPPPPPPPPNNNNNNNNNNNNNFFFFFEEEXXXXIGGGGSSSSSSSSSKKKKKK
    IIIIITTTTGGGGGGGGGSSSSSSYYYYYYYYYYYYNNNNNNNNNNNNNNAMMMMMMMMIIIIIIIIKKKKKKKKKKKLBBLLVVPPPPPPPPPPNNNNNNNNNNNNNFFFFFFEEXXXXIGGGGSSSSSEEKKKKKKKK
    IIITTTTTTGGGGGGGGGGGSSSSSYYYYYYYYYYYVNNNNNNNNNNNNNNUMMMIIMIIIIIIIIKKKKKKKKKKKKBBBBLLLLPPPPPPPPPPNNNNNNNNNBNBFJFFEFEEXXXXXGGGGGSSEEEEKKEKKKKK
    IIITTTTTTGGGGGGGGGGGSRSSSSYYYYYYYYYYYYNXNNNNNNNNNNNNCMMIIIIYYIIIIIKKKKKKKKKGGKBBBBLLLLPPPPPLPPPPNNNNNNNNBBDDDJFFEEEXXXXXJJGGJGSSREEEEEEKCKKK
    IIITTTTTTGGGGGGGGGGGGRRRYYYYYYYYYYYYYYXXNWWNNNNNNNNNCMMXXIYYYIYIIIIKKKKKKKKKKKBBBBLLLLLLPPPLPPPPWWNNNINNNDDDDDEEEEEXXXXXJJJJJJSHEEEEEEEECKKC
    IXIIIIITPPPGGGGGGGGGGRRRRYYYYYYYYYYYYYYYWWWNNNNNNNNNNMXXXXXYYYYYYIIKKKKKKKKKRKBBBBBXXXLPPPPLPPPPWWANIIIIIDDDDDDDEEFXXXXXXXEEEESEEEEEEEECCKCC
    XXXXXIIIPPGGGGGGGGGGGRRRRRYYYYYYYYYYYYYYYWNNNNNNNNXXXXXXXXYYYYYYYYYKKKKKKKKKKBBBBBBXXXLLLLLPPPPWWWAIIIIIIDDEEDEEEFFFXXXXXEEEEEEEEEEEECCCCCCC
    XXXXIIIIIPGGGGGGGGRRRRRRRYYYYYYKYYYYKYXXXJWNNNNNNXXXXXXXXXYYYYYYYYYAAKKKKKKKKBBBBBBXXXXXXXLLVPWWWWAAAIIIDDDDEEEFEFFFXXXEEEEEEEEEEEEEEECCCCCC
    XXXXXIIIPPGGGGGGGGRRRRRRRYYYYYYKYYKKKKXXXJJSNNNNXXXXXXXXXYYYYYYYYYAAKKKKKKKKBBBBBBBBBXXXXXLLVPAAWWAAAAIIDDDDJEEFFFFFXXXEEEEEEEEEEEEEECCCCCCC
    XXXXSSSSWWWWPGGNNNRRRRRRRRYYYYKKKKKKKXXXXJJJJNNNXXXXXXXXXYYYYYYYYYYAAUUKKKKKBBBBBBBBBXXXXXXAAJAAAWAAIITTTTIIJEFFFFFXXXXEEEEEEEEEEEEECCCCCCCC
    XXXXXWWWWWWWGGNNNNRRRRRRRRYYYKKKKKKKKKXXXXXJJJNNXXXXXXXXXYYYYYYYYYAAAAKKLKKBBBBBBBBBBXXXXXXAAAAAAAAAAATTTTIJJJXFFFFXFXXFEEEEEEEEEEECCCCCCCCC
    XXXXTWWWWWWWWGWNNRRRWRRRRRMYYJJKKKKKKXXXXJJJJJJNXXXXXXXXYYYYYYYYYYAAAAAALLLLBBBBBBBBXXXXXXAAAAATTTTTTTTTTTIJJJFFFFFFFFFFFEEEEEEEEEEECCCCCCCC
    HTTTTJWWWWWWWGWRRRRWWRRRRRYYYJJKKKKKKKXJJJJJJJJJJXXXXXXXYYYYYYYYYAAAAAALLLLLBWBBBBBBXZZZXXAAAAATTTTTTTTTTTJJJJJFFFFFFFFFFEEEEEEEEEEECCCCCCCC
    TTTTWWWWWWWWWWWWWWWWRRRRRYYJJJWWKKKKKKKKJJJJJJJJJXXXXXXXUYYYYYYAAAAAAAALLLLLLBBBBBBBBZZZAAATTTTTTTTTTTTTTTTJJFFFFFFFFFFEEEEEEEEEEEEOCCCCCCCC
    VVTTWWWWWWWWWWWWWWYYYYURRWYJWWWWKKKKKMKJJJJJJJJJXXXXXXXXUYYYYYYAAAAAAAALLLLLLBBBBBBZZZZZAAATTTTTTTTTTTTTTTTJJJFFFFFFFFFEEEQEEEEEEEEOCPCCCCCC
    VVTWWWWWWWWWWWWWWWYYYYYPWWWWWWWWKKKKKMMJJJJJJJJJEEXJJNVXVVSVVVVVVAAAAAALLLLLLLLLSVSZZZZAAAATTTTTTTTTTTTTTTTJJJFFFFFFFFFFEEEEEEEEOOOOCCCCCCCC
    VVVWWWWWWWWWWWYYYYYYYYYYYWWWWWWWWKKKKMMMJJJJJJJEEENNNNNNVVVVVCVVVVAFAAFLLLLLLLLXSSSZZIZAAAATTTTTTTTTTTTTTTJJJJFFFFFFFFFEEEEBEEEEEZZZZCCCCCCC
    VVVWWWWWWWIWWWCYYYYYYYYYYWWWWWWWWWKKKMMMMMJJJJJJENNNNNNNVVVVVVVVVVFFFFFFLLLLXXXXDSSZIIAAAAATTTTTTTTTTTTTJJJJJJJKFFFFFFEEEEZBZEDZZZZZZCCCCCCJ
    VVWWWWWWWWWWWWYRRYYYYYYYYWWWWWWWWWWKPPPPPMMMMMJJJNNNNNNVVVVOVVVVVVFFFFFFFLLXXXVXSSSIIIAAAAATTTTTTTTTTTTTJJJJJJJFFFFSTTEEEEZZZZZZZZZZZCCCCCJJ
    DDDWWWWWWWWWWYYYYYYYYYYYWWWWWWWWWWWPPPPPPPMMMMJJJZNNNNNVVVVVVVVVVFFFFFFFFFXXXXXXSSSIIIAAAAATTTTTTTTTTTTTJJJJJJFFFYFFTTTTTEZZZZZZZZZZZZZCCCJJ
    DDBWWWWWWWWWWYYYYYYYYYYYWWWWWWWWWWWPPPPPPPPMMMMMJZZNNNNVVVVVVVVVVFNFFFFFFFXXXXXXSSIIIIAIAAATTTTTTTTTTTTTJJJJJJJJFYYTTTTTTEZZZZZZZZZZZZZYCCCC
    DDDDWWWWWWWWWYYYYYYYYYYYYWWWWWWWWWPPPPPPPPPPMMIIIZZNNNNNNNVVVVVVVVNFFFFFFFXXXXXXSSIIIIIIIAATTTTTTJJJJJJJJJJJUUUYYYJTTTTTTZZZZZZZZZZZZZZYYCCR
    DDDWWWWWWWWWWYYYYYYYYYYYYWWWWWWWWPPPPPPPPPPPIIUIIIZIINNNNVVVVVVFFNNFFFFFFFFXXXXXSSSTTIIXSAATTTTTTJJJJJJJJJJJUUUPJJJJTTTCCZZZZZZZZZZZZZZYYWCR
    DDDDWWWWVWWWWYIGYYYYYYYYYWWWWWWWLLPPPPPPPPPPIIIWWWWWIINNNNNNVVVFSFNFNFFFFFFXXXXXXXXXXXHXSAAAHZZZZZHHZZJJJJJVUUUPJJJJTTTTTFFFFZZZZZZZZZWWYWWR
    VDWWWWWVVVWGWYGGYYYYYYYYYWWWWWWWPPPPPPPPPPPIIIIWWWWWINNNNNNNNNNFFFNNNFFFFFXXXXXXXXXXXHHXSAXHHHZZHHHHZZJJJJJVUUUPJJJTTTTTTTFFFFFZZZZWWZWWWWWW
    VWWVWWVVVVWGGGGGYYYYYVPYYYWWWLWLLPPPPPPPYPDIIIIWWWWWINNRNNNNNNFFFFFNNFFKFXXXXXXXXXXXXHXXXXXXHHHHHHHZZZJJJJGVVUPPJPGTTTTTCTFFFFFZWWWWWWWWWWEE
    VVVVWUVVVVVGGGGGGGGZZPPPPYWWWLLLPPPPPPPPPIIIIIIWWWWWRRRRNNNNNNFFFFFFFFFFFXXXXXXXXXXXXHHXXXXXHHHHHHHHHHJJJJGGPPPPPPPBGGTTTTFFOFFZWWWWWWWWWWEE
    VVVVWVVVVVVFGGGGGGPPPPPPPPPPWLLLPPPPPPPPPPIIIIIWWWWWNNNNNNNNNFJFFFFFFFFFFFXQXXXXXXXXXHHXXXXXHHHHHHHHHHGGGGGGPGGPGBBBGGGGJOOFOFOOWWWWWWWWWWWW
    VVVVWVVVVVVVVVGGGXXXPPPPPPPPILLPPPPPPPLPYYIIIIIWWWWWNNNNNNNNNFFFFFFFFFFFFFQQHHXHHXXXDFHHHHHHHHHHHHHHHHGGGGGGGGGGGGBGGGGGOOOOOOOHWWWWWWWWWWWW
    VVVVVVVVVVVVVVVVVXXXXXXPPPPPILLPPPPPPPPYYXIIIIIWWWWWWWWWWWNNNNFFFFFFFFFFFFFQHHHHHXHFFFFFFHHHHHHHHHHHHHHGGGGGGGGGEEGGGGGGOOOOOOOWWWWWWWWWWWWW
    VVVVVVVVVVVVVVVVXXXXXXXXPPPPILIIIPIPLLPYXXIPIIIWWWWWWWWWWWNNNFFFFFFFFFFFFFYQHHHHHHHFFPFFFHHHHHHHHHHHHHHGGGGGGGGGGEEEGGGGGOOGOOWWWWWWWWWWWWWT
    VVVVVVVVVVVVVVVVVVXXXXXPPPPPIIIIIIIIIIIIPXXXIIIWWWWWWWWWWWNNNFLFPPFFFFFFFFYQHHHHHHHFFFFFFHHHHHHHHHHHHHHGGGGGGGGEEEEGGGGGGGGGGGGWWWWWWWWWWWTT
    VVVVVVVVVVVVVVVVVVXXXXXXXPIIIIIIIIIIIIIIPXXXXXIIWWWWWWWWWWNNNNNNPPPFFFFFFFYHHHHHHFFFFFFFFFFFHFFFHHHHHHHGGGGGGGGGEEEGGGGGGGGGGBBYWWWTWWWWWTTT
    VVVVVVVVVVVVVVVVVXXXXXXXXPPIIIIIIIIIIIIKXXXXXXXIWWWWWWWWWWNNNNPPPPPFFFFFHHYYHHHHFFFFFFFFFFFFFFFZHHHHHHHHGGGGGGGGEPGDDGGGBBBGBBBYYYBTWWWWTTTT
    VVVVVVVVVVVVVVVVVVXXSSSSSYSSIIIIIIIIIXKKXXXXXXXIWWWWWWWWWWNNPPPPPPFFFFFHHHYYHHHHFFFFFFFFFFFFFFPZZHZHHHHHHHGGGKKGPPGGGGGGBBBGBBBBBBBTWWWTTTTT
    VVVVVVVVVVVVVVVVVXXXSSSSSSSSFFFIIIIIIXXKXXXXXXXXWWWWWWWWWWNNNPPPPPPPFFHHHHHHHHHHFFFFFFFFAFFFFPZZZZZHHHHHHHGGKKSSPPPOOGGGBBBBBBBHBBBBBDBBTTTT
    VVVVVWVVVVVVVVVVUSXSSSSSSMMMMFIIIIIIIXXXXXXXXXXXXXWWWWWNNNNNNNNPPPFFFFFFHHHHHHHHFFFFFFFAAAFFFZZZZZZZHHHHHHGGKKKPPOOOOGGBBBBBBBBHHBBBBBBTTTTT
    VVVVVWWVVVVVVVVVUSSSSSSSSSMMMFFIIIIIIXXXXXXXXXXXXXWWWWWEMNNNNNNPPPPPFHFHHHHHHHHFFFFFFFFFFFFFFDZZZZZLHHHHHHHSKKKPPPPOOOGGLBBBBBZBBBBBBBTTTTTT
    VWWVWWWWWVVVVVUUUUSSSSSSSSSMMFFIIIIIXXIXXXXXXQQQQXWWWWWEMIMNMWMPMMPPPHHHHHHHHHHHHFFFFFFFFFCCCZZZZZZLHIIHHHHSSKPPPPPOOOGOBBBBBBBBBBBBBBTTTTTT
    VWWWWWWWWWWWVUUUUUSSSSSSSMMMPFFFIPIIIIIIXXXQQQQQQQWWWWWMMIMMMMMMMMMPPPHHHHHHHHHHQSFFFFFFFCCCCZZZZZZLHHHHHHHSSSSPPPOOOOOOBBBBBBBBBBBBBTTTTTTT
    WWWWWWWWWWWWWUUUUUSSSSSSSSMMPFPPIPPIIIIIXXXQQQQQQQQQQQMMMMMMMMMMMMMMPPHHHHHHJJJJSSSSFFCCCCCZZZZZZLLLSSSHHHHSSSSSSOOOOOOOOOBOOSSBBBBBBTTTTTTT
    WWWWWWWWWWWWWUUUUGCSSSSSSSMPPPPPPPPPIIIIQQXQQQQQQQQQQQQMMMMMMMMMMMMMPMMDHHHHJSSSSSSSSCCCLLLZZZZZZLLLLSSSSSSSSSSSSSOOOOOOOOOOSSSSSBBBBBTTTTTT
    WWWWWWWWWWWWUUUUUGCSSSSSMMMPPPPPPPPPPIIIJQQQQQQQQQQQQQQQQMMMMMMMMMMMMMDDDHHDSSSSSSSSSCCLLLLZZZZZZLLLLSSSSSSSSSSSSSSOOOOOOOOOSSSSSSSBTBBTTTTT
    WWUWWWWWWWWWUUUUUGSSMSSMMGMPPPPPPGEEEEEEJJQNQQQQQQTQQQQQQMMMMMMMMMMMMMMDDHHDSSSSSSSSSSSLLLLZZZZZZLLLLLSSSXSSSSSSSOOOOOOOOOOOSSSSSSSTTTTTTTTT
    WWWWWWWWWWWWUUUUUGSSMMMMMGMPPPPPPPPEEEEEEJQQQQQQTQTTTTQYAAAAAAAMMMMMMMMDDDDDSSSSSSSSSSSSLLLLLZZLZLLLLLSSSSSSSSSSSOOOOOOOOOOSSSSSSSSTTTTTITII
    WSSSSSWWWWWWWUGGGGSSSMMMMGGPPPPPPPEEEEEEEEQQQRRTTQTTTLJYAAAAAAAAAAMMMMMDDDDDDDSSSSSSSSSSLLLLLLLLLLLLLLSSLSSSSSSSOOOOOOOOOOOOOOSSSTTTTTTIIIII
    TTSSSSSSWWWWTGGGGGGGGGMMMGGDDDPPPPEEEEEEEEQQQTTTTTTTTLJJAAAAAAAAAAMMMDMMDDDDDDSSSSSSSSSLLLLLLLLLLLLLLLLLLLSSSSSOOOOOOOOOOOOOSSSSSSSTTTIIIIII
    SSSSSSSSSWWTTGGGGGGGGGGGMGGGGGPPPPEEEEEEEEERRTTTTTTTTJJJAAAAAAAAAAMDDDDDDDDDDDSSSSSSSSSSLSSLLLLLLJJZJLLLLLLCSCCCCCOOOEEEOOOSSSSSSSSSIIIIIIII
    SSSSSSSSSSWWTGGGGGGGGGGGGGGGGGEEEEEEEEEEEERRRRTTTTTTTJJJAAAAAAAAAAMPPDDDDDDDDSSSSSSSSSSSSSJJJJJLLJJJJJBBBCCCCCCCCCCOOEEEEEEESSSSSSSSSSIIIIII
    YSSSSSSSSSLWTTJGGGGGGGGGGGGGGGEEESEEEEEMERRTTTTTTTTTTJJJAAAAAAAAAAPPPDDDDDDDDSSSSSSSSSSSSAAJJJJJJJJJJBBBBCCCCCCCCCCEEEEEEKESSSPVVSSSIIIIIIII
    YSSSSSSSSSJJTTJJJGGGGGGGGGGGGSSSSSEKMMMMMRRRTTTTTTTJJJJJAAAAAAAAAAPPPDDDDDDDSSSSSSSSSSSSSSAAJJJJJJJJJBBBBBCCCCCCCCCEEEEEEERRSSVVVVVVDDIIIIII
    YSSSSYYSSWJJJJJJJJJGGGGGGGGXGSSSSUUKKMMMRRRRTTTTTTTJJAAAAAAAAAAAAARRPPDDDDPPXSSSSSSSSSSSSSAAAJJJJJJJJBBBBBBBCCCCDDEEEEEEEEERSVVVVVVVVVIIIIII
    YYSSSYYYYJJJJJJJJJGGGGGGGGGGSSSSUUUKMMMMMMRRRTTTTTTJJAAAAAAAAAAAAAPPPPPPDDPPXXSSSSSAAAAAAAAAJJJJJJJJJJJJJJBBCCCCDZZZEEEEEEEENVVVVVVVVVIIIIII
    YYSYYYYJJJJJJJJJJGGGGGGGGGGSSSUSUUMMMMMMMMRTTTTTTJTJJAAAAAAAAAAAAAPPPPPPPPPPPXSXSSSAAAAAAAAAJJJJJJJJJJJJJJBBBBBBZZZZEEEEEEEEVVVVVVVVVVIIFIII
    YYYYYYYJJJJJJJJJJJJJGGGGGGGSSSUSUUMMMMMMMMMMBBTTJJJJJAAAAAAAYYRRPPPPPPPPPPPPPXXXSXXKAAAAAAAAJJKJJJJJJJJJJJBBBZZZZZZZEEEEEERRRVVVVVVVVVVVFFFF
    YYYYYJJJJJJJJJJJFFJJJGGGGGGUUUUUUMMMMMMMMMMMMBTTTJJJJAAAAAAAYYRPPPPPPPPPPPPPPXXXXXXKKKKKAAAJJJJJJJJJJJJJBBBBBZZZZZZZEEEEEEVVVVVVVVVVVVVVVFFZ
    YYYYYJJJJJJJJJJJJJJJIIIGGGUUUUUUUMMMMMMMMMMMBBTTJJJJJAAAAAAAYYRPPPPPPPPPPPOOXXXXXXXKKKKKKAAZIIJJJJJJJJJJBBBBBBBZZZEEEEEEEEEVVVVVVVVVVVVVVVZZ
    YYYYJJJJJJJJJJJJJJJJIITTGGUUUUUUUUMMMMMMMMMMMMJJJJJJJAAAAAAARRRPPPPPPPPPPPOOOXXXXXXKKKKKKKAZIIZJJJJJJJJJBBBBBBBBZZZEEEEEEVEVVVVVVVVVVVVVVFOZ
    YYYYYJJJJJJJJJJJJJJJIIIIIIUUUUUUUUCCCMMMMMMMMMMMMJJJJJJYYYYYYRYYPPPPPPPOOOOOOXXXKKKKKKKKKKZZZZZJJJJJJJJJBBBBBBBBBSZUEEEEEVVVVVVVVVVVQOOVOOOZ
    YYYYYJJJJJJJJJJJJJZZIIIIIIUUUUUUUUUUUMMMMMMMMMMMMJJJJJJJYYYYYYYYPPPPPPPOOOOOOOOOKKKKKKKKKZZZZZZJZZJJJJJJBBBBBBBBBBBUUUEEEEVVVVVVVVVVVOOOOOOZ
    YYYYYJJJJJJJJJJJJMBIIIIIIIIUUUUUUUUUUMMMMMMMMMMJJJJJJJJJJYYYYYYYYYYPPPPOOOOOOOOOKKKKKKKKKZZZZZZZZZJJJJHJBBBBBBBBBBBUUUEUUUUVVVVVVVVVVOOOXXOZ
    YYYYYJJJJJXXJJJJBBBDIIIIIIEUUUUUUUUUUMMMMMZKFFMMJJJJJJJJJYDYYJYYYYYYYPPOOOOOOOOOOOKKKKKKKZZZZZZZZZZJJJHHHHBBBBBBBBBUUUUUUVVVUVVVZVBBOOOOXXOO
    YYYYYJYYJJHXHJJJBBBDIIIIEEEEEUUUUUUUUMFMMMKKKKCCCJJJJJJJJJDDYYYYYYYYPPPOOOOOOOOOOOKKKKKKKZZZZSZZZZZJJJHHHHNBBBBBBUUUUUUUUUUUUVJVVVOOOOOOOXOO
    YYYYYYYYHHHHHHHBBBBIIIIIEEEEEUUUUUUNNMFMFFKLKKCCJJJJJJJJJJDDYYYYYYYYPPPOOOOOOOOOOKKKKKKKKKZZZZZZZZZJJIKHHHNNBBBBBUUUUUUUUUUUCSCMVEEOOOOOOOOO
    YYYYYYYYYRXHXHBBBBBIIIIEEEEUUUUUUUUUUFFFFFFKKKKCJJJJJJJJJMYYYYYYYYYYYOOOYYOOOOOOOOKKKKKKKKZZZZZZZZZZKKKHHNNNNNBBBUUUUUURRUCCCCCCEEEOOOOOOOOO
    YYYYYYYYYRHHHBBBBBBBBBBBBBBKUUUUUUUUUUUFFFFKKKKKKJUCCCCCCYYYYYYYYYYYYYYOOOOOOOOOOOOKKKKKKKKKZZZZZZZZKHHHNNNNNNBBBUUUURRRQCCCCCCCEEOOOOOOOOOO
    YYYYYYYYYRBBBBBBBBBBBBBBBBBKUUUUUUUUUUUUKFKKKKKKKUUCECCCCDYYYYYYYYYYYYYAOOOOOOOSOOKKKQQQKKKKKZZZZZKKKHHHHHNNNNNNNNRRRRRRQCCCCCCCEELOOOOOOOOO
    YYYYYYYYRRRBBBBBBBBBBBBBBBSUUUUUUUUUUUUAKKKKKKKCKCCCCCCCCDDYYYYYYYYYYYYAAOOOOOOOHHKKKQQQKKKKZZZRZZKKKHHKKHNNNUNNNRRRRRRRCCCCCCCTLLLOOOOOOOOO
    YYYYKUUUUUBBBBBBBBBBBBBBBBSSUUTUUUUUUUAAKAKKKKKCCCCCCCCCCCCWYYYYYYYYYYYYYHOOBOOHHHQQQQQQQQQQBBBBZZZKKKKKKHKKKKNNNRRRRRRRCCCCCCCCLLVOOOOOOOOO
    YYYYKKUUUUUBBUUUBBBBBBBBBBSSSUUSUUUUUUAAAAKKKKKKKCCCCCCCCCCCCCCYYYYYYHHHHHHOOOHHHHQAQQQQQQQQBBBZZKKKKKKKKKKKKYYNNRRRRRRCCCCCCCCCLLLLOOOOOOOO
    YYKKKKUUUUUUUUUBBBBBBBBBBBSSSUSSUUUSAAAAAKKKKKKKKCCCCCCCCCCCCCCYYYYYYYHHHHHOHHHHHQQQQQQQQQQQBBBBBKKKKKKKLKKKKYYYRRRRRRCCCCCCCCCCLCJJZZZODOOS
    YYKKKKKUUUUUUUUBBBBBBBBBBBBBSSSSSUUSAQAAAKKKKKKKKKCCCCCCCCCCZZZYYYYYYHHHHHHHHHHHHHQQQQQQQQQQBBBIBKKKKKKKKKKKKKRRRRRRRRCCCCCCCCCCCCJZZZZOOOOS
    YKKKKKKKKKUUUUGBBBBBBBBPPBBBSSSSSUSSSQQKKKKKKKKKKKCCCCCCCCCCCCHHHYHYHHHHHHBBBBHHHHQQQQQQQQBBBBBBBKBKKKKKKKKKKKKRRRRRRRCCCCCCCCCCTCCZZZZZZZOS
    KKKKKKKKKUUUUUUBBBBPPPPPPPSSSSSSSSSSSQKKKKKKKKKKKKCTCCCCCCCCYCHHHHHHHHBHHBBBBHHHHQQQQQQQQQQBBBBBBKBKKKKKKKKKKKRRRRRRRRRRCCCCCCCCTTZZZZZZZZSS
    KKKKKKKKKKUUUUUBBBBPPPPPPPSSSSSSSSSSSQKKKKKKKKKKKKCCCCCCCCCYYYYYHHHHHHBBBBBBBGGGHQQQAQQQQQQQQBBBBBBKKKKKKEEEKKRRRRRRRRRRZCCCCCCCTTZZZZZZZZZZ
    KKKKKKKUUUUUUUUUBBBPPPPPPPSSSSSSSSSSSQKOKKKKKKKKKKCCCCCCCCYYYYYYHHHHHHBBBBBBBGGGHHGGGQQQQQEEEEBBBBBBKKEKKEEEEERRRRRRRRRRCCTTCCCCTTTZZZZZZZZZ
    EKKKKKKKKKUJUUUUBBBBPPPPPPSSSSSSSSSSSSSSKKKKKKKKKKCCCCCCCCYYYYYYHHHHHHBBBBBBUGGGHGGGGGQQQQEEEEEEEBBBBKEKEEEEEERRRRRLRRRRRRTTKKKKTZZZZZZZZZZU
    KKKKKKKKKKUJUUAABJBBPPPHPPSSSSSSSSSSSSSKKKCKKKKKKKCCCRRRCCCYYYYYYHHHHBBBBBBBUGGGGGGGQQQQQQQEEEEEEBBBBEEEEEEEEEEERELLLLRRRRTTKKKKTTTTZZZZZZUU
    GKKKKKKKKUUUUUUGGJJPPPPHHPSSSSSSSSSSSSSSSSCCCKKKKKCKRRRRRRYYYYYYHHHHHHBBBBBBBGGGGGGQQQQQQQEEEEEHHBBBEECCCEEEEEEEEELLLLRRLLTKKKKKTTTTZZZZZZUU
    GKKKKKKKKUUGUGGGGJHHPPPHHPSHHSSSSSSSSSSSCCCCCKKKKKKKRRYYYYYYYYYYYHHHHBBBBBBBJGGGGGGGQQQQQEEEEEEHHBBBCCCCCCEEEEEEEELLLLRRQLTTKKKKTTTTZUZZZUUU
    GGKKKKKKKAGGGGGGJJJJJJJJJJHHHHSSSSSSSSSSCCCCKKKKVKKRRRRRYYYYYYYYHHHHHHBBBBBBJGGGGGGGQQQHQQQQEEHHHCCCXCCCEEEEEEEEEELLLLLLLLTTTKKKTTTTZZZZZZZU
    GGGKKKKKKGGXGGGGJJJJJJJJJJHHHVVVSSSSSSSSCCCCCCCVVVRRRRRRYOYVYCCHHHHHHHBBBBJJJGGGGGGGQHQHHHEEEHHHHCCCCCCCCEEEEEEELLLLLLLLLLTTTTTTTTTTTTTTZZZU
    GGKKKKKKGGGGGGGGJJJJJJJJJJHHHVSSSSCSSSCCCCCCCCCVVVVRRVVVVVVVVHHHHHHHHHHBIBGGGGGGGGGGHHHHHHHEHHHHHCCCCCCCCCCCEEELLLLLLLLLLLLTTTTTTTTTTTTTTTZD
    GGKKKKKKGGGGGGGGJJJJJJJJJJHHHVWQSCCCCCCCCCCCDCVVVVVVVVVVVVVVMHHHHHHHHHQBBBGQGGTGGGGGDHHHHHHHHHHHHCCCCCCCCCCEEEELLLLLLLLLLLLTTTTTTTTTTTTTTTTD
    GGGKGGGGGGGGGGGGJJJJJJJJJJHSHWWWWCCCCCCCCCFFFFFVVVVVVVVVVVVVMHHMHMMMMMQQQQQQQQGGGGHHHHHHHHHHHHHHPPCCCCCCCCMQQEELLLLLLLLLLLTTTTTTTTTTTTTTTTTD
    GGGGGGGGGGGGGGGGJJJJJJJJJJSSWWSWWCCCCCCCCDFFFFFVJVVVVVVVVVVVMHHMMMMMMQQQQQQQQQGGQQHHHHHHHHHHHHHHCCCCCCCCCCCQQQLLLLLLLLLLLLLTLKKKKTTTDDTDDDDD
    UUUUGUGGGGGGGGGGJJJJJJJJJJSSSSSSCCCCGCGFFFFFFFFDVVVVVVVVVVVMMMMMMMMQQQQQQQQQQQQQQQHHHHHHHHHHHHCCCCCCCCCCCCCQQLLLLLLLLLLLLLLTLKKKKTTTDDDDDDDD
    UUUUUUUGGGGGGGGGGGLLBBHMSSSSSSSSSGGGGGGFFFFFFFFDDDVVVVVVVVVMMMMMQQQQQQQQQQQQQQQQHHHHHHHHHHHHHHHCCCCCCCCCCCCQQLLLLLLLLLLLLLLLLKKKKTTTDDDDDDDD
    UUUUUUUUGGGGGGGGGGLBBHHSSSSSSSSSGGGGGGGFFFFFFFFDDDVVVVVVVVMMMMMMMMQQQQQQQQQQQQQQHHHHHHHHHHHHHHHCCCCCCCCCCQQQLLLLLPLLLLLLLLLLLLKKKKTTTDDDDDDD
    UUUUUUUUGGGGGSSSGLLLBSSSSSSSSSSSSGGGGGGFFFFFFFDDDDDVVVVVVVMMMMMMQQQQQQQQQQQQQQQPTTHHHHHHHHHHHHHCCCCCCCCCQQQQQQLBBPLLLAALLLLKKKKKKKKTTDDDDDDD
    UUUUUUUUUUUGSSSSSBBBBBSSSSSSSSSSSRGGGGGFFFFFDDDDDDDVVVVVVVVMMMMMMMMQQQQQQQQQQQQPTTTHHHHHHHHHHHHCCCCCCCCQQQQQQQBBBBWLAAAALLLKKKKKKKTTDDDDDDDD
    UUUUUUUUDUSGSSSSSSBBBBBSSSSSSSSSRRGGGGGFFFFFCDDDDDDVVVVVVCCMMMMMMMMMMQQQPPQPQPQPPTTHHHHHHHHHHHCCCCCCPCCQQQQQBBBBBBBAATTAATLKKKKKKKDDDDDDDDDD
    UUUUUUUUUUSSSSSSSSBBBBSSSSSSSSSSRRGGGGGGFFFFCCDDDDDTTTVVVCCCCMMMMMMMMMQPPPPPPPPPPTHHHHHKKHHHHHHCCCCCQCQQQQQQBBBBBBBBATTTTTTTTKKKKNNNNDDDDDDD
    UUUUUUUUUUSSSSSSSSBSSSSSSSSSSSSSSGGGGGGGGGCCCCCDDDDDDTVVVCCCCCMMMMMMMAATPPPPPPPPPTHHHHHKKHHHHHHCCCCQQQQQQQQBBBBBBBBBTTTTTTTTTKKKKKKNNNDDDDDD
    UUUUUUUUSUSSSSSSSSSSSSSSSSSSSSSWGGGGGGGGGGCCCCCDDDDDDDDVVCCCCCMMMMMMMAAATPPPPPPPTTHKKKKKKHHHHHCCCQQQQQQQQQBBBBBBBBBTTOTTTTTTLKKKKKKNNNDDDDDD
    UUUUUUSSSSSSSSSSSSSSSSSSSSSSSSSWPGGGGGGGGGCCCCCGDDIIIDHVVVCCCCCMMMMMAAAAPPPPPPPEEEKKKEKEEHHHHHHCQQQQQQQQQQQBBBBBBBZTTTTTTTTTKKKKEKKGGGGGGGDG
    UUUUUUUUSSSSSSSSSSSSSSSUUSSSSWSWWGGGGCGGGGCCCCCCCIIIICCCCCCCCCCCJJMAAAAPPPPPPEEEEEEEEEEEEEEHHHHHHQQQQQQQQQQBBBBBBBZZTTTTTTTTTKKKKKKGGGGGGGGG
    UUUUBUSUSSAAAASSSSSSSSSUUUSSSWWWWGGGGCGGCCCCCCCCCIIIIICCCCCCCCCCCCAAAAAAPPAAEEEEEEEEEEEEEEEHHHHHQQQCQQQQQQQBBBBBBBZZTTTTTTTTTTBKGGKGGHHGGGGG
    DDUUUSSSSAAAAAAASSSSSSSSUUUWWEWVWGFGCCCCCCCCCCCCIIXXXICCCCCCCCCCAAAAAAAAPPPAPPPEEEEEEEEEEUUUUUHHMQQQQQQQQQQQBHBBBBBTTTTTTTTTTTTGGGGGHHHGHGGG
    DUUUUSSSSSBBAAAASSSSSSSUUUWWWWWVWFFFFFCCCCCCCCCCXXXXXCCNCCCCCCCCAAAAAAAAPAAAPPEEEEEEEEEEEUEEEUUZZQQQQQQQQQNZHHHBBBBTTTTTTTTTTTTGGGGGHHHHHGGG
    DDDDUDDSSSSAAAAAASSSSUUUUUWWWWWWWWFFFCCCCCCCCCCCXXXAXACCCCCCCCCCCAAAAAAAAAAAAPEEEEEEEEEEEEEEEUZZZZQQQQQQQQZZZHHHBBBSTTTTTTTTTTGGGGGHHHHHGGGG
    DDDDDDDSSSZAAAAAASSSUUUUUUWWWWWWWWFFFFFFCCCCCCCCCXXAAACECCCCCCCCCCAAAAAAAAAAAAAEEEEEEEEEEEWZUUUZZZZQZQZQQQZHHHHHHHBTTTTTTTTTTTGGGGGHHGHGGGGG
    DDDBDDDDSDAAAAAAAUUUUUUUUUWWWWWWWWFFFFCCCCCCCCCCCCAACCCCCCCCJCCCAAAAAAAAAAAAAAEEEEEEEEEEEEEZZUUZZZZZZZZQZZZHZHHHHHHHHTTTTTTTTGGGGGGHHGGGGGGG
    DDDBBDDDSDDDDAAVVVUUUUUUUUUWWWFWWFFFFFCCCCCCCCCCCCCCCCCCCCCJATAAAAAAAAAAAAAAAAAAEEEEEEEEEEEZZZZZZZZZZZZZZZZZZHHHHHHHHTTTTTTTGGGGGGGHHGGGGGGG
    DDDBBBDDDDDDDDAAAAAUUUUUUUUWFFFFFFFFFCCCCCCCCCCCCCCCCCJCCCCJAAAAAAAAAAAAAAAAAAAAEEEYYEEYYEEESSZZZZZZZZZZZZZZHHHHHHHHTTTTTTTGGGGGGGGGGGGGGGGG
    DDDBBDDDDDDDDDDDAQQQUUUUUUUFFFFFFFFFFFFCCCCCCCCCCCCKCCJJJJJJAAAAAAAAAAAAAAAAAAAEEEYYYYYYYYESSSSSZZZZZZZZZZZZHHHHHHHHHTTTTTTGGGGGGGGGGGGGGGGG
    """;

    static List<Point> directions = List.of(new Point(0, -1), new Point(0, 1), new Point(-1, 0), new Point(1, 0));

    static int maxX;
    static int maxY;

    private static char[][] convertToCharArray(String input) {
        String[] inputArr = input.trim().split("\n");

        char[][] inputCharArray = new char[inputArr.length][];

        for (int i = 0; i < inputArr.length; i++) {
            inputCharArray[i] = inputArr[i].toCharArray();
        }

        return inputCharArray;
    }

    private static void dfs(int x, int y, Set<Point> overallPath, char[][] gardenPlot, Plant plant) {
        for (Point delta: directions) {
            int newX = x + delta.x;
            int newY = y + delta.y;

            if (Math.min(newX, newY) < 0 || newX >= maxX || newY >= maxY) {
                createPerimeterCoordinate(x, y, delta, plant);
                continue;
            }

            Point newCoordinates = new Point(newX, newY);

            if (gardenPlot[newX][newY] == plant.type && !plant.path.contains(newCoordinates)) {
                // No perimeter between plants of same type
                // plant.perimeter += 0;

                // Add new coordinates to overall and plant paths
                overallPath.add(newCoordinates);
                plant.path.add(newCoordinates);

                // Search for other nearby plants of same type
                dfs(newX, newY, overallPath, gardenPlot, plant);
            } else if (gardenPlot[newX][newY] != plant.type) {
                // Nearby plant is not of same type, therefore a perimeter is available
                createPerimeterCoordinate(x, y, delta, plant);
            }
        }
    }


    private static void createPerimeterCoordinate(int x, int y, Point delta, Plant plant) {
        String direction = null;
        if (delta.x == 0) {
            direction = "horizontal";
        } else if (delta.y == 0) {
            direction = "vertical";
        }

        double perimeterX = x + delta.x / 4.0;
        double perimeterY = y + delta.y / 4.0;

        plant.perimeterCoordinates.add(
            new Side(perimeterX,  perimeterY, direction)
        );
    }


    private static List<Side> getAdjacentCoordinates(Side perimeterCoordinate) {
        List<Side> adjacentCoordinates = new ArrayList<>();
        if (perimeterCoordinate.direction.equals("horizontal")) {
            Side increase = new Side(perimeterCoordinate.x + 1.0, perimeterCoordinate.y, "horizontal");
            adjacentCoordinates.add(increase);
            Side decrease = new Side(perimeterCoordinate.x - 1.0, perimeterCoordinate.y, "horizontal");
            adjacentCoordinates.add(decrease);
        }
        else if (perimeterCoordinate.direction.equals("vertical")) {
            Side increase = new Side(perimeterCoordinate.x, perimeterCoordinate.y + 1.0, "vertical");
            adjacentCoordinates.add(increase);
            Side decrease = new Side(perimeterCoordinate.x, perimeterCoordinate.y - 1.0, "vertical");
            adjacentCoordinates.add(decrease);
        }
        return adjacentCoordinates;
    }


    private static void findAllSideCoordinates(Side startingSideCoordinate, Plant plant) {
        // Create queue
        List<Side> coordinatesOfSide = new ArrayList<>();
        List<Side> startingPotentialCoordinates = getAdjacentCoordinates(startingSideCoordinate);

        for (Side coordinate: startingPotentialCoordinates) {
            if (plant.perimeterCoordinates.contains(coordinate)) {
                coordinatesOfSide.add(coordinate);
            }
        }


        while (!coordinatesOfSide.isEmpty()) {
            // System.out.println("coordinatesOfSide: " + coordinatesOfSide.toString());

            // Remove Side coordinate from array and from plant perimeter coordinates
            Side first = coordinatesOfSide.removeFirst();
            plant.perimeterCoordinates.remove(first);

            // Get adjacent coordinates
            List<Side> potentialCoordinates = getAdjacentCoordinates(first);

            for (Side coordinate: potentialCoordinates) {
                // Add adjacent coordinates if they are in plant perimeter coordinates
                if (plant.perimeterCoordinates.contains(coordinate)) {
                    coordinatesOfSide.add(coordinate);
                }
            }
        }
    }

    private static void calculateSides(Plant plant) {
        // System.out.println("plant.perimeterCoordinates: " + plant.perimeterCoordinatesToString());
        // Searches for sides as long as there are permemterCoordinates left
        while (!plant.perimeterCoordinates.isEmpty()) {
            Side nextSideCoordinate = plant.perimeterCoordinates.iterator().next();
            plant.perimeterCoordinates.remove(nextSideCoordinate);

            // System.out.println("plantType " + plant.type + ", nextSideCoord: " + nextSideCoordinate);

            findAllSideCoordinates(nextSideCoordinate, plant);

            // System.out.println();

            plant.sides += 1; // Increase the sides of the plant region once all side coordinates have been deleted
        }
    }

    public static void main(String[] args) {
        char[][] inputCharArray = convertToCharArray(input);

        maxX = inputCharArray.length;
        maxY = inputCharArray[0].length;

        Set<Point> overallPath = new HashSet<>();

        List<Plant> allPlants = new ArrayList<>();

        for (int x = 0; x < maxX; x++) {
            for (int y = 0; y < maxY; y++) {
                Point currentCoordinate = new Point(x, y);
                if (!overallPath.contains(currentCoordinate)) {
                    // Initialise a new plant region
                    char plantType = inputCharArray[x][y];
                    Plant region = new Plant(plantType);
                    region.path.add(new Point(x, y)); // Add starting coordinate to plant path

                    dfs(x, y, overallPath, inputCharArray, region);

                    region.area = region.path.size();
                    allPlants.add(region);
                }
            }
        }

        System.err.println("allPlants: " + allPlants.toString() + "\n");

        for (Plant plant: allPlants) {
            calculateSides(plant);
        }

        int totalPrice = 0;

        for (Plant plant: allPlants) {
            // For debugging
            // System.err.println("\nplant: " + plant.toString());
            totalPrice += plant.area * plant.sides;
            System.out.println("Region of " + plant.type + " plant with sides * area = price; " + plant.sides + " * " + plant.area + " = " + (plant.area * plant.sides));
        }

        System.err.println("totalPrice: " + totalPrice);
    }
}

class Plant {
    char type;
    int area;
    int perimeter;
    Set<Point> path;
    Set<Side> perimeterCoordinates;
    int sides;

    public Plant(char type) {
        this.type = type;
        this.path = new HashSet<>();
        this.perimeterCoordinates = new HashSet<>();
    }

    @Override
    public String toString() {
        return "{type="+type + ", area="+area + ", sides="+sides +"}";
    }

    public String perimeterCoordinatesToString() {
        return perimeterCoordinates.toString();
    }
}

class Side {
    double x, y;
    String direction;

    public Side(double x, double y, String direction) {
        this.x = x;
        this.y = y;
        this.direction = direction;
    }

    @Override
    public String toString() {
        return "{x="+x + ", y="+y + ", direction="+direction +"}";
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Side other)) return false;
        return Double.compare(x, other.x) == 0 && Double.compare(y, other.y) == 0;
    }

    @Override
    public int hashCode() {
        return Objects.hash(x, y);
    }
}

